### ISSUE TITLE
map function from Option package thows error in typescript

### ISSUE THREAD

**Issue by izaika** [PacoteJS/pacote#130]
Hi,
I have an issue with 'option' package. Could you please help?

Copied example from the docs:

```typescript
import { map, None, Option, Some } from '@pacote/option';

function divide(numerator: number, denominator: number): Option<number> {
  return denominator === 0 ? None : Some(numerator / denominator);
}
map(n => n + 1)(divide(4, 2));
```

Get an error: `error TS2365: Operator '+' cannot be applied to types 'unknown' and '1'. 
13 map(n => n + 1)(divide(4, 2));`

![image](https://user-images.githubusercontent.com/31729165/115542263-c4822100-a2a8-11eb-9fca-c1b759a3bf56.png)

![image](https://user-images.githubusercontent.com/31729165/115542346-dc59a500-a2a8-11eb-823e-3af6e6c176b2.png)

Typescript version: 4.2.3

**Comment by goblindegook** [comment]
Unfortunately in some instances we are not able to infer the type. In this case, writing it as `map((n: number) => n + 1)(divide(4, 2));` will clear the error.

You can also use the `@pacote/pipe` package to write it as `pipe(divide(4, 2), map(n => n + 1))`, which correctly infers the `n` argument type.

**Comment by izaika** [comment]
Thanks

**Comment by goblindegook** [comment]
In the meantime, I also updated the README, which I realised was out of date. Sorry about that.
